import type { MiniAppManifest } from "@shared/types/miniapp-manifest";

export const manifest: MiniAppManifest = {
  name: "Fruit Funnel",
  description: "A real-physics fruit-merge game: drop fruit, let gravity stack them, and merge matching pairs into bigger fruit without letting the pile cross the danger line.",
  icon: "sparkles",
  category: "game",
  shell: "game",
  supportsGuest: true,
  supportsGameFi: false,
  gamePage: {
    categoryColor: "#16C784",
    modes: { guest: true, gamefi: false },
    heroBadgeKey: "localOnly",
    heroTitleKey: "appTitle",
    heroTitleAccent: "appTitle",
    heroDescKey: "appSubtitle",
    primaryLabelKey: "startAction",
    ghostLabelKey: "rulesTitle",
    featuresEyebrowKey: "appEyebrow",
    featuresTitleKey: "featureBoardTitle",
    features: [
      {
        titleKey: "featureBoardTitle",
        descKey: "featureBoardCopy",
        large: true,
        gradient: "linear-gradient(135deg, #E8F9EF 0%, #9BE7C4 48%, #16C784 100%)",
      },
      { titleKey: "featureRecoveryTitle", descKey: "featureRecoveryCopy" },
      { titleKey: "featureInputTitle", descKey: "featureInputCopy" },
    ],
    ctaTitleKey: "appTitle",
    ctaDescKey: "appSubtitle",
    ctaLabelKey: "startAction",
    trustBadgeKeys: ["localOnly", "fairnessTitle", "featureInputTitle"],
  },
  tabs: [{ key: "play", labelKey: "playTab", icon: "grid", default: true }],
  stats: [],
  sidebar: { titleKey: "rulesTitle", items: [] },
  operations: [],
  docs: [
    { titleKey: "rulesTitle", contentKey: "rulesCopy", type: "steps" },
    { titleKey: "fairnessTitle", contentKey: "fairnessCopy", type: "text" },
  ],
  features: {
    walletRequired: false,
    chainWarning: false,
    fireworks: true,
    activityFeed: false,
    reviews: true,
    comments: true,
  },
  permissions: { payments: false, randomness: false, compute: false, oracle: false },
};
