-- =============================================================================
-- OneGate Vault production hardening
-- =============================================================================
-- Keeps the QR-key reward flow server-side and auditable:
--   - exposed RPC is a service-role-only wrapper, not a SECURITY DEFINER body
--   - atomic claim reservation lives in the private schema
--   - claim state changes are recorded in an append-only event table
--   - RLS remains enabled and public roles receive no direct table access

BEGIN;

CREATE EXTENSION IF NOT EXISTS pgcrypto;

CREATE SCHEMA IF NOT EXISTS private;
REVOKE ALL ON SCHEMA private FROM PUBLIC;
GRANT USAGE ON SCHEMA private TO service_role;

CREATE TABLE IF NOT EXISTS public.onegate_vault_campaigns (
  id TEXT PRIMARY KEY,
  app_id TEXT NOT NULL DEFAULT 'miniapp-onegate-vault',
  network TEXT NOT NULL CHECK (network IN ('mainnet', 'testnet')),
  creator_address TEXT,
  reward_source TEXT NOT NULL DEFAULT 'PLATFORM_SPONSOR',
  status TEXT NOT NULL DEFAULT 'active' CHECK (status IN ('active', 'paused', 'expired')),
  min_amount_fixed8 NUMERIC(39, 0) NOT NULL DEFAULT 100000000 CHECK (min_amount_fixed8 >= 100000000),
  max_amount_fixed8 NUMERIC(39, 0) NOT NULL DEFAULT 5000000000 CHECK (max_amount_fixed8 >= min_amount_fixed8 AND max_amount_fixed8 <= 5000000000),
  remaining_amount_fixed8 NUMERIC(39, 0) NOT NULL CHECK (remaining_amount_fixed8 >= 0),
  max_claims INTEGER NOT NULL CHECK (max_claims > 0),
  claimed_count INTEGER NOT NULL DEFAULT 0 CHECK (claimed_count >= 0),
  expires_at TIMESTAMPTZ,
  metadata JSONB NOT NULL DEFAULT '{}'::jsonb,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS public.onegate_vault_claim_keys (
  key_hash TEXT PRIMARY KEY,
  campaign_id TEXT NOT NULL REFERENCES public.onegate_vault_campaigns(id) ON DELETE CASCADE,
  network TEXT NOT NULL CHECK (network IN ('mainnet', 'testnet')),
  status TEXT NOT NULL DEFAULT 'unused' CHECK (status IN ('unused', 'pending', 'submitted', 'paid', 'failed')),
  wallet_address TEXT,
  amount_fixed8 NUMERIC(39, 0),
  tx_hash TEXT,
  request_id TEXT,
  error_message TEXT,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  claimed_at TIMESTAMPTZ,
  submitted_at TIMESTAMPTZ,
  paid_at TIMESTAMPTZ,
  failed_at TIMESTAMPTZ,
  CONSTRAINT onegate_vault_claim_key_amount_nonnegative CHECK (amount_fixed8 IS NULL OR amount_fixed8 > 0)
);

ALTER TABLE public.onegate_vault_claim_keys
  ADD COLUMN IF NOT EXISTS updated_at TIMESTAMPTZ NOT NULL DEFAULT now();

ALTER TABLE public.onegate_vault_campaigns
  ALTER COLUMN min_amount_fixed8 SET DEFAULT 100000000,
  ALTER COLUMN max_amount_fixed8 SET DEFAULT 5000000000;

ALTER TABLE public.onegate_vault_campaigns
  DROP CONSTRAINT IF EXISTS onegate_vault_campaigns_min_amount_fixed8_check,
  DROP CONSTRAINT IF EXISTS onegate_vault_campaigns_max_amount_fixed8_check,
  DROP CONSTRAINT IF EXISTS onegate_vault_campaigns_min_amount_fixed8_1_50,
  DROP CONSTRAINT IF EXISTS onegate_vault_campaigns_max_amount_fixed8_1_50;

ALTER TABLE public.onegate_vault_campaigns
  ADD CONSTRAINT onegate_vault_campaigns_min_amount_fixed8_1_50
    CHECK (min_amount_fixed8 >= 100000000),
  ADD CONSTRAINT onegate_vault_campaigns_max_amount_fixed8_1_50
    CHECK (max_amount_fixed8 >= min_amount_fixed8 AND max_amount_fixed8 <= 5000000000);

ALTER TABLE public.onegate_vault_claim_keys
  DROP CONSTRAINT IF EXISTS onegate_vault_claim_keys_status_check,
  ADD CONSTRAINT onegate_vault_claim_keys_status_check
    CHECK (status IN ('unused', 'pending', 'submitted', 'paid', 'failed'));

CREATE TABLE IF NOT EXISTS public.onegate_vault_claim_events (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  key_hash TEXT NOT NULL REFERENCES public.onegate_vault_claim_keys(key_hash) ON DELETE CASCADE,
  campaign_id TEXT NOT NULL REFERENCES public.onegate_vault_campaigns(id) ON DELETE CASCADE,
  network TEXT NOT NULL CHECK (network IN ('mainnet', 'testnet')),
  event_type TEXT NOT NULL CHECK (event_type IN ('reserved', 'submitted', 'paid', 'failed')),
  wallet_address TEXT,
  amount_fixed8 NUMERIC(39, 0),
  tx_hash TEXT,
  request_id TEXT,
  error_message TEXT,
  metadata JSONB NOT NULL DEFAULT '{}'::jsonb,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE UNIQUE INDEX IF NOT EXISTS idx_onegate_vault_claim_keys_request_id
  ON public.onegate_vault_claim_keys (request_id)
  WHERE request_id IS NOT NULL;

CREATE INDEX IF NOT EXISTS idx_onegate_vault_claim_keys_campaign_status
  ON public.onegate_vault_claim_keys (campaign_id, status, created_at DESC);

CREATE INDEX IF NOT EXISTS idx_onegate_vault_claim_keys_wallet
  ON public.onegate_vault_claim_keys (network, wallet_address, created_at DESC)
  WHERE wallet_address IS NOT NULL;

CREATE INDEX IF NOT EXISTS idx_onegate_vault_campaigns_network_status
  ON public.onegate_vault_campaigns (network, status, created_at DESC);

CREATE INDEX IF NOT EXISTS idx_onegate_vault_claim_events_campaign_created
  ON public.onegate_vault_claim_events (campaign_id, created_at DESC);

CREATE INDEX IF NOT EXISTS idx_onegate_vault_claim_events_key_created
  ON public.onegate_vault_claim_events (key_hash, created_at DESC);

CREATE INDEX IF NOT EXISTS idx_onegate_vault_claim_events_network_type
  ON public.onegate_vault_claim_events (network, event_type, created_at DESC);

ALTER TABLE public.onegate_vault_campaigns ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.onegate_vault_claim_keys ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.onegate_vault_claim_events ENABLE ROW LEVEL SECURITY;

REVOKE ALL ON TABLE public.onegate_vault_campaigns FROM anon, authenticated;
REVOKE ALL ON TABLE public.onegate_vault_claim_keys FROM anon, authenticated;
REVOKE ALL ON TABLE public.onegate_vault_claim_events FROM anon, authenticated;
GRANT SELECT, INSERT, UPDATE, DELETE ON TABLE public.onegate_vault_campaigns TO service_role;
GRANT SELECT, INSERT, UPDATE, DELETE ON TABLE public.onegate_vault_claim_keys TO service_role;
GRANT SELECT, INSERT, UPDATE, DELETE ON TABLE public.onegate_vault_claim_events TO service_role;
GRANT USAGE, SELECT ON SEQUENCE public.onegate_vault_claim_events_id_seq TO service_role;

DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_policies
     WHERE schemaname = 'public'
       AND tablename = 'onegate_vault_campaigns'
       AND policyname = 'service_all_onegate_vault_campaigns'
  ) THEN
    CREATE POLICY service_all_onegate_vault_campaigns
      ON public.onegate_vault_campaigns
      FOR ALL TO service_role
      USING (true)
      WITH CHECK (true);
  END IF;

  IF NOT EXISTS (
    SELECT 1 FROM pg_policies
     WHERE schemaname = 'public'
       AND tablename = 'onegate_vault_claim_keys'
       AND policyname = 'service_all_onegate_vault_claim_keys'
  ) THEN
    CREATE POLICY service_all_onegate_vault_claim_keys
      ON public.onegate_vault_claim_keys
      FOR ALL TO service_role
      USING (true)
      WITH CHECK (true);
  END IF;

  IF NOT EXISTS (
    SELECT 1 FROM pg_policies
     WHERE schemaname = 'public'
       AND tablename = 'onegate_vault_claim_events'
       AND policyname = 'service_all_onegate_vault_claim_events'
  ) THEN
    CREATE POLICY service_all_onegate_vault_claim_events
      ON public.onegate_vault_claim_events
      FOR ALL TO service_role
      USING (true)
      WITH CHECK (true);
  END IF;
END;
$$;

CREATE OR REPLACE FUNCTION private.onegate_vault_set_updated_at()
RETURNS TRIGGER
LANGUAGE plpgsql
SET search_path = ''
AS $$
BEGIN
  NEW.updated_at = pg_catalog.now();
  RETURN NEW;
END;
$$;

DROP TRIGGER IF EXISTS trg_onegate_vault_campaigns_updated_at
  ON public.onegate_vault_campaigns;
CREATE TRIGGER trg_onegate_vault_campaigns_updated_at
  BEFORE UPDATE ON public.onegate_vault_campaigns
  FOR EACH ROW
  EXECUTE FUNCTION private.onegate_vault_set_updated_at();

DROP TRIGGER IF EXISTS trg_onegate_vault_claim_keys_updated_at
  ON public.onegate_vault_claim_keys;
CREATE TRIGGER trg_onegate_vault_claim_keys_updated_at
  BEFORE UPDATE ON public.onegate_vault_claim_keys
  FOR EACH ROW
  EXECUTE FUNCTION private.onegate_vault_set_updated_at();

CREATE OR REPLACE FUNCTION private.onegate_vault_claim_key_event_audit()
RETURNS TRIGGER
LANGUAGE plpgsql
SET search_path = ''
AS $$
DECLARE
  v_event_type TEXT;
BEGIN
  IF TG_OP <> 'UPDATE' THEN
    RETURN NEW;
  END IF;

  IF NEW.status = OLD.status
     AND NEW.tx_hash IS NOT DISTINCT FROM OLD.tx_hash
     AND NEW.error_message IS NOT DISTINCT FROM OLD.error_message THEN
    RETURN NEW;
  END IF;

  v_event_type := CASE NEW.status
    WHEN 'pending' THEN 'reserved'
    WHEN 'submitted' THEN 'submitted'
    WHEN 'paid' THEN 'paid'
    WHEN 'failed' THEN 'failed'
    ELSE NULL
  END;

  IF v_event_type IS NULL THEN
    RETURN NEW;
  END IF;

  INSERT INTO public.onegate_vault_claim_events (
    key_hash,
    campaign_id,
    network,
    event_type,
    wallet_address,
    amount_fixed8,
    tx_hash,
    request_id,
    error_message,
    metadata
  )
  VALUES (
    NEW.key_hash,
    NEW.campaign_id,
    NEW.network,
    v_event_type,
    NEW.wallet_address,
    NEW.amount_fixed8,
    NEW.tx_hash,
    NEW.request_id,
    NEW.error_message,
    pg_catalog.jsonb_build_object('previous_status', OLD.status)
  );

  RETURN NEW;
END;
$$;

DROP TRIGGER IF EXISTS trg_onegate_vault_claim_key_event_audit
  ON public.onegate_vault_claim_keys;
CREATE TRIGGER trg_onegate_vault_claim_key_event_audit
  AFTER UPDATE OF status, tx_hash, request_id, error_message ON public.onegate_vault_claim_keys
  FOR EACH ROW
  EXECUTE FUNCTION private.onegate_vault_claim_key_event_audit();

CREATE OR REPLACE FUNCTION private.onegate_vault_reserve_claim(
  p_key_hash TEXT,
  p_wallet_address TEXT,
  p_network TEXT,
  p_request_id TEXT,
  p_random_u64 NUMERIC DEFAULT NULL
)
RETURNS TABLE (
  key_hash TEXT,
  campaign_id TEXT,
  network TEXT,
  status TEXT,
  wallet_address TEXT,
  amount_fixed8 TEXT,
  tx_hash TEXT,
  request_id TEXT
)
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = ''
AS $$
DECLARE
  v_key public.onegate_vault_claim_keys%ROWTYPE;
  v_campaign public.onegate_vault_campaigns%ROWTYPE;
  v_capped_max NUMERIC(39, 0);
  v_span NUMERIC(39, 0);
  v_random NUMERIC(39, 0);
  v_amount NUMERIC(39, 0);
BEGIN
  IF p_network NOT IN ('mainnet', 'testnet') THEN
    RAISE EXCEPTION 'INVALID_NETWORK';
  END IF;

  IF p_wallet_address IS NULL OR pg_catalog.length(pg_catalog.btrim(p_wallet_address)) < 20 THEN
    RAISE EXCEPTION 'INVALID_ADDRESS';
  END IF;

  SELECT *
    INTO v_key
    FROM public.onegate_vault_claim_keys
   WHERE onegate_vault_claim_keys.key_hash = p_key_hash
     AND onegate_vault_claim_keys.network = p_network
   FOR UPDATE;

  IF NOT FOUND THEN
    RAISE EXCEPTION 'CLAIM_KEY_NOT_FOUND';
  END IF;

  IF v_key.wallet_address IS NOT NULL AND v_key.wallet_address <> p_wallet_address THEN
    RAISE EXCEPTION 'CLAIM_KEY_USED';
  END IF;

  IF v_key.wallet_address = p_wallet_address
     AND v_key.amount_fixed8 IS NOT NULL
     AND v_key.request_id IS NOT NULL THEN
    RETURN QUERY
      SELECT
        v_key.key_hash,
        v_key.campaign_id,
        v_key.network,
        v_key.status,
        v_key.wallet_address,
        v_key.amount_fixed8::TEXT,
        v_key.tx_hash,
        v_key.request_id;
    RETURN;
  END IF;

  SELECT *
    INTO v_campaign
    FROM public.onegate_vault_campaigns
   WHERE onegate_vault_campaigns.id = v_key.campaign_id
     AND onegate_vault_campaigns.network = p_network
   FOR UPDATE;

  IF NOT FOUND THEN
    RAISE EXCEPTION 'VAULT_NOT_FOUND';
  END IF;

  IF v_campaign.status <> 'active' THEN
    RAISE EXCEPTION 'VAULT_INACTIVE';
  END IF;

  IF v_campaign.expires_at IS NOT NULL AND v_campaign.expires_at <= pg_catalog.now() THEN
    RAISE EXCEPTION 'VAULT_EXPIRED';
  END IF;

  IF v_campaign.claimed_count >= v_campaign.max_claims
     OR v_campaign.remaining_amount_fixed8 < v_campaign.min_amount_fixed8 THEN
    RAISE EXCEPTION 'VAULT_EMPTY';
  END IF;

  IF v_campaign.min_amount_fixed8 < 100000000
     OR v_campaign.max_amount_fixed8 > 5000000000
     OR v_campaign.min_amount_fixed8 > v_campaign.max_amount_fixed8 THEN
    RAISE EXCEPTION 'INVALID_REWARD_RANGE';
  END IF;

  v_capped_max := LEAST(v_campaign.max_amount_fixed8, v_campaign.remaining_amount_fixed8);
  v_span := v_capped_max - v_campaign.min_amount_fixed8 + 1;
  IF v_span <= 0 THEN
    RAISE EXCEPTION 'VAULT_EMPTY';
  END IF;

  IF p_random_u64 IS NULL OR p_random_u64 < 0 THEN
    v_random := pg_catalog.floor(pg_catalog.random() * 9223372036854775807)::NUMERIC;
  ELSE
    v_random := pg_catalog.floor(p_random_u64);
  END IF;
  v_amount := v_campaign.min_amount_fixed8 + pg_catalog.mod(v_random, v_span);

  UPDATE public.onegate_vault_campaigns
     SET remaining_amount_fixed8 = remaining_amount_fixed8 - v_amount,
         claimed_count = claimed_count + 1,
         updated_at = pg_catalog.now()
   WHERE id = v_campaign.id;

  UPDATE public.onegate_vault_claim_keys
     SET status = 'pending',
         wallet_address = p_wallet_address,
         amount_fixed8 = v_amount,
         request_id = p_request_id,
         error_message = NULL,
         claimed_at = pg_catalog.now(),
         failed_at = NULL
   WHERE onegate_vault_claim_keys.key_hash = p_key_hash
   RETURNING *
    INTO v_key;

  RETURN QUERY
    SELECT
      v_key.key_hash,
      v_key.campaign_id,
      v_key.network,
      v_key.status,
      v_key.wallet_address,
      v_key.amount_fixed8::TEXT,
      v_key.tx_hash,
      v_key.request_id;
END;
$$;

REVOKE ALL ON FUNCTION private.onegate_vault_reserve_claim(TEXT, TEXT, TEXT, TEXT, NUMERIC) FROM PUBLIC;
GRANT EXECUTE ON FUNCTION private.onegate_vault_reserve_claim(TEXT, TEXT, TEXT, TEXT, NUMERIC) TO service_role;

DROP FUNCTION IF EXISTS public.onegate_vault_reserve_claim(TEXT, TEXT, TEXT, TEXT);
CREATE OR REPLACE FUNCTION public.onegate_vault_reserve_claim(
  p_key_hash TEXT,
  p_wallet_address TEXT,
  p_network TEXT,
  p_request_id TEXT
)
RETURNS TABLE (
  key_hash TEXT,
  campaign_id TEXT,
  network TEXT,
  status TEXT,
  wallet_address TEXT,
  amount_fixed8 TEXT,
  tx_hash TEXT,
  request_id TEXT
)
LANGUAGE sql
SECURITY INVOKER
SET search_path = ''
AS $$
  SELECT *
    FROM private.onegate_vault_reserve_claim(
      p_key_hash,
      p_wallet_address,
      p_network,
      p_request_id,
      NULL::NUMERIC
    );
$$;

CREATE OR REPLACE FUNCTION public.onegate_vault_reserve_claim_v2(
  p_key_hash TEXT,
  p_wallet_address TEXT,
  p_network TEXT,
  p_request_id TEXT,
  p_random_u64 TEXT
)
RETURNS TABLE (
  key_hash TEXT,
  campaign_id TEXT,
  network TEXT,
  status TEXT,
  wallet_address TEXT,
  amount_fixed8 TEXT,
  tx_hash TEXT,
  request_id TEXT
)
LANGUAGE sql
SECURITY INVOKER
SET search_path = ''
AS $$
  SELECT *
    FROM private.onegate_vault_reserve_claim(
      p_key_hash,
      p_wallet_address,
      p_network,
      p_request_id,
      NULLIF(p_random_u64, '')::NUMERIC
    );
$$;

REVOKE ALL ON FUNCTION public.onegate_vault_reserve_claim(TEXT, TEXT, TEXT, TEXT) FROM PUBLIC;
REVOKE ALL ON FUNCTION public.onegate_vault_reserve_claim_v2(TEXT, TEXT, TEXT, TEXT, TEXT) FROM PUBLIC;
GRANT EXECUTE ON FUNCTION public.onegate_vault_reserve_claim(TEXT, TEXT, TEXT, TEXT) TO service_role;
GRANT EXECUTE ON FUNCTION public.onegate_vault_reserve_claim_v2(TEXT, TEXT, TEXT, TEXT, TEXT) TO service_role;

COMMIT;
