import type { Badge, UserLevel } from "./types";

export const LEVELS: UserLevel[] = [
  { level: 1, name: "Newcomer", minXP: 0, maxXP: 100, color: "text-gray-400", perks: [] },
  { level: 2, name: "Explorer", minXP: 100, maxXP: 300, color: "text-emerald-500", perks: ["Profile badge"] },
  { level: 3, name: "Contributor", minXP: 300, maxXP: 600, color: "text-blue-500", perks: ["Custom avatar"] },
  { level: 4, name: "Veteran", minXP: 600, maxXP: 1000, color: "text-violet-500", perks: ["Priority support"] },
  { level: 5, name: "Pioneer", minXP: 1000, maxXP: 2000, color: "text-amber-500", perks: ["Beta access"] },
  { level: 6, name: "Legend", minXP: 2000, maxXP: 5000, color: "text-red-500", perks: ["Exclusive events"] },
];

export const BADGES: Badge[] = [
  {
    id: "early_adopter",
    name: "Early Adopter",
    description: "Joined during beta phase",
    icon: "🌟",
    category: "special",
    rarity: "legendary",
    requirement: "Join before mainnet launch",
    points: 500,
  },
  {
    id: "first_tx",
    name: "First Transaction",
    description: "Completed your first transaction",
    icon: "💫",
    category: "achievement",
    rarity: "common",
    requirement: "Complete 1 transaction",
    points: 50,
  },
  {
    id: "power_user",
    name: "Power User",
    description: "Completed 100 transactions",
    icon: "⚡",
    category: "activity",
    rarity: "rare",
    requirement: "Complete 100 transactions",
    points: 200,
  },
  {
    id: "voter",
    name: "Active Voter",
    description: "Participated in governance",
    icon: "🗳️",
    category: "achievement",
    rarity: "common",
    requirement: "Cast 1 governance vote",
    points: 100,
  },
  {
    id: "whale",
    name: "Whale",
    description: "Hold significant assets",
    icon: "🐋",
    category: "achievement",
    rarity: "epic",
    requirement: "Hold 10,000+ GAS",
    points: 300,
  },
  {
    id: "developer",
    name: "Developer",
    description: "Deployed a MiniApp",
    icon: "👨‍💻",
    category: "special",
    rarity: "epic",
    requirement: "Deploy a verified MiniApp",
    points: 400,
  },
  {
    id: "streak_7",
    name: "Week Warrior",
    description: "7-day activity streak",
    icon: "🔥",
    category: "activity",
    rarity: "common",
    requirement: "7 consecutive active days",
    points: 70,
  },
  {
    id: "streak_30",
    name: "Monthly Master",
    description: "30-day activity streak",
    icon: "💎",
    category: "activity",
    rarity: "rare",
    requirement: "30 consecutive active days",
    points: 300,
  },
];
