#!/usr/bin/env node

import crypto from "node:crypto";
import fs from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";

const scriptDir = path.dirname(fileURLToPath(import.meta.url));
const repoRoot = path.resolve(scriptDir, "..", "..");
const buildDir = path.join(repoRoot, "contracts", "build");
const outputPath = path.join(
  repoRoot,
  "apps",
  "shared",
  "factory",
  "generated-template-artifacts.ts",
);

const definitions = {
  nep17: "FactoryNep17Token",
  nep11: "FactoryNep11Collection",
};

function sha256Hex(value) {
  return `0x${crypto.createHash("sha256").update(value).digest("hex")}`;
}

function readArtifact(name) {
  const nef = fs.readFileSync(path.join(buildDir, `${name}.nef`));
  const manifestText = fs.readFileSync(
    path.join(buildDir, `${name}.manifest.json`),
    "utf8",
  );
  const manifest = JSON.parse(manifestText);
  return {
    contractName: name,
    nefBase64: nef.toString("base64"),
    nefSha256: sha256Hex(nef),
    manifest: JSON.stringify(manifest),
    manifestSha256: sha256Hex(Buffer.from(JSON.stringify(manifest), "utf8")),
  };
}

const artifacts = Object.fromEntries(
  Object.entries(definitions).map(([kind, name]) => [kind, readArtifact(name)]),
);
const source = `// Generated by deploy/scripts/generate_factory_template_artifacts.mjs.\n` +
  `// Do not edit by hand; rebuild contracts, then regenerate this file.\n\n` +
  `export const FACTORY_TEMPLATE_ARTIFACTS = ${JSON.stringify(artifacts, null, 2)} as const;\n`;

if (process.argv.includes("--check")) {
  const current = fs.existsSync(outputPath) ? fs.readFileSync(outputPath, "utf8") : "";
  if (current !== source) {
    console.error(
      `${path.relative(repoRoot, outputPath)} is stale; run npm run generate:factory-template-artifacts`,
    );
    process.exit(1);
  }
  console.log(`Verified ${path.relative(repoRoot, outputPath)}`);
  process.exit(0);
}

fs.writeFileSync(outputPath, source);
console.log(`Generated ${path.relative(repoRoot, outputPath)}`);
