apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: service-layer

resources:
  - ../prod

patches:
  - target:
      kind: ConfigMap
      name: service-layer-config
    patch: |-
      - op: replace
        path: /data/NITRO_ENV
        value: "testing"

labels:
  - includeSelectors: true
    includeTemplates: true
    pairs:
      environment: staging-nitro
