import { mergeMessages } from "@shared/locale/base-messages";
import { getNetwork } from "@shared/constants/rpc";
import type { MiniAppManifest } from "@shared/types/miniapp-manifest";

export const appId = "miniapp-oracle-vrf-console";

export function resolveNetworkLabel(): string {
  return getNetwork() === "testnet" ? "Neo N3 Testnet" : "Neo N3 Mainnet";
}

export const manifest: MiniAppManifest = {
  name: "Oracle VRF Workbench",
  description:
    "Build an exact Morpheus randomness request, inspect live network bindings, and verify a response against the selected network's pinned Morpheus worker signer.",
  icon: "shield-check",
  category: "oracle",
  shell: "console",
  theme: { family: "default", accentColor: "#0f9f8f", density: "comfortable" },
  tabs: [{ key: "vrf", labelKey: "tabVrf", icon: "shield-check", default: true }],
  stats: [
    { labelKey: "statNetwork", valueKey: "networkLabel", format: "text", icon: "globe" },
    { labelKey: "statService", valueKey: "serviceLabel", format: "text", icon: "activity" },
    { labelKey: "statRequest", valueKey: "lastDigest", format: "text", icon: "key" },
  ],
  sidebar: {
    titleKey: "appName",
    items: [
      { labelKey: "statNetwork", valueKey: "networkLabel", format: "text" },
      { labelKey: "statService", valueKey: "serviceLabel", format: "text" },
      { labelKey: "lastStatus", valueKey: "lastStatus", format: "text" },
    ],
  },
  features: { walletRequired: false, chainWarning: true },
  docs: [
    { titleKey: "docsTitle", contentKey: "docsSubtitle", type: "text" },
    { titleKey: "feature1Name", contentKey: "feature1Desc", type: "features" },
    { titleKey: "feature2Name", contentKey: "feature2Desc", type: "features" },
    { titleKey: "feature3Name", contentKey: "feature3Desc", type: "features" },
  ],
  permissions: { storage: true },
};

const appMessages = {
  appName: { en: "Oracle VRF Workbench", zh: "预言机随机数工作台" },
  title: { en: "Oracle VRF", zh: "预言机随机数" },
  tabVrf: { en: "VRF Workbench", zh: "随机数工作台" },
  panelEyebrow: { en: "Morpheus randomness operations", zh: "Morpheus 随机数运维" },
  panelTitle: { en: "VRF Verification Workbench", zh: "随机数验证工作台" },
  heroCopy: {
    en: "Create the exact Morpheus request body, hand it to an authenticated consumer integration, then verify the returned randomness against the selected network's pinned response signer.",
    zh: "生成准确的 Morpheus 请求体，交给已认证的消费者集成提交，再使用所选网络固定的回执签名密钥验证随机数。",
  },
  heroAlt: {
    en: "A bright Oracle verification studio with a signed randomness capsule and network instruments.",
    zh: "明亮的预言机验证工作室，配有签名随机数胶囊和网络仪表。",
  },
  workspaceCaption: { en: "Randomness control room", zh: "随机数控制室" },
  workspaceTitle: { en: "Request, bind, verify", zh: "请求、绑定、验证" },

  statNetwork: { en: "Network", zh: "网络" },
  statService: { en: "Service boundary", zh: "服务边界" },
  statRequest: { en: "Request", zh: "请求" },
  lastStatus: { en: "Current state", zh: "当前状态" },
  digestPlaceholder: { en: "No draft", zh: "尚无草稿" },
  networkMainnet: { en: "Neo N3 Mainnet", zh: "Neo N3 主网" },
  networkTestnet: { en: "Neo N3 Testnet", zh: "Neo N3 测试网" },

  serviceChecking: { en: "Checking bindings", zh: "正在检查绑定" },
  serviceNotChecked: { en: "Not checked yet", zh: "尚未检查" },
  serviceNotCheckedCopy: {
    en: "Live service and chain bindings are only read when you ask. Run Refresh bindings to fetch health, key, and callback evidence.",
    zh: "只有在您主动请求时才会读取服务与链上绑定。点击“刷新绑定”获取健康、密钥和回调证据。",
  },
  serviceProtected: { en: "Integration only", zh: "仅限集成调用" },
  serviceMismatch: { en: "Network mismatch", zh: "网络不匹配" },
  serviceDegraded: { en: "Degraded", zh: "服务降级" },
  serviceUnavailable: { en: "Unavailable", zh: "不可用" },
  serviceStale: { en: "Cached status", zh: "缓存状态" },
  serviceBoundaryTitle: { en: "Live service boundary", zh: "实时服务边界" },
  serviceBoundaryCopy: {
    en: "This page performs read-only health, key, contract, and callback checks. It never POSTs to /vrf/random.",
    zh: "本页面仅执行健康、密钥、合约和回调的只读检查，绝不会向 /vrf/random 发起 POST。",
  },
  serviceRuntime: { en: "Runtime", zh: "运行时" },
  serviceNetwork: { en: "Reported network", zh: "上报网络" },
  responseSigner: { en: "Response signer", zh: "回执签名密钥" },
  fulfillmentVerifier: { en: "On-chain fulfillment key", zh: "链上履约密钥" },
  serviceKey: { en: "Fulfillment key binding", zh: "履约密钥绑定" },
  serviceCallback: { en: "Callback binding", zh: "回调绑定" },
  callbackConsumer: { en: "Callback consumer", zh: "回调消费者" },
  serviceQueue: { en: "Contract requests", zh: "合约请求" },
  serviceFee: { en: "Request fee", zh: "请求费用" },
  serviceReady: { en: "Ready", zh: "正常" },
  serviceNotReady: { en: "Not ready", zh: "未就绪" },
  serviceBound: { en: "Bound", zh: "已绑定" },
  serviceNotBound: { en: "Not bound", zh: "未绑定" },
  servicePinned: { en: "Network-pinned", zh: "已按网络固定" },
  serviceNotPinned: { en: "Not pinned", zh: "尚未固定" },
  serviceRoleSeparation: {
    en: "Response signatures use the worker key; contract fulfillment uses the separate Oracle verifier key.",
    zh: "回执签名使用 worker 密钥；合约履约使用独立的预言机验证密钥。",
  },
  serviceWorkflowMissing: { en: "VRF is not advertised in the public workflow catalog", zh: "公开工作流目录未声明 VRF" },
  serviceAuthRequired: { en: "Submission requires an authenticated consumer or contract integration", zh: "提交需要已认证的消费者或合约集成" },
  serviceFreshAt: { en: "Checked {time}", zh: "检查于 {time}" },
  serviceCachedAt: { en: "Last live check {time}; refresh before trusting a key", zh: "上次实时检查于 {time}；信任密钥前请刷新" },
  refreshService: { en: "Refresh bindings", zh: "刷新绑定" },
  refreshingService: { en: "Refreshing bindings", zh: "正在刷新绑定" },

  pipelineTitle: { en: "One clear verification path", zh: "一条清晰的验证路径" },
  stepDraft: { en: "1. Draft", zh: "1. 草稿" },
  stepDraftCopy: { en: "Create the exact request_id + target_chain body.", zh: "生成准确的 request_id + target_chain 请求体。" },
  stepSubmit: { en: "2. Submit externally", zh: "2. 外部提交" },
  stepSubmitCopy: { en: "Use a protected Morpheus consumer path; this app does not dispatch.", zh: "使用受保护的 Morpheus 消费者通道；本应用不负责提交。" },
  stepVerify: { en: "3. Verify response", zh: "3. 验证回执" },
  stepVerifyCopy: { en: "Paste the signed JSON and verify key, hash, signature, and request correlation.", zh: "粘贴签名 JSON，验证密钥、哈希、签名和请求关联。" },
  pipelinePending: { en: "Pending", zh: "待处理" },
  pipelineComplete: { en: "Complete", zh: "已完成" },
  pipelineExternal: { en: "External", zh: "外部完成" },

  useCaseTitle: { en: "Randomness use case", zh: "随机数使用场景" },
  useCaseGame: { en: "Game outcome", zh: "游戏结果" },
  useCaseGameHint: { en: "Loot, map, matchmaking", zh: "掉落、地图、匹配" },
  useCaseRaffle: { en: "Raffle draw", zh: "抽奖开奖" },
  useCaseRaffleHint: { en: "Winner selection", zh: "赢家选择" },
  useCaseAllocation: { en: "Fair allocation", zh: "公平分配" },
  useCaseAllocationHint: { en: "Order or seat assignment", zh: "顺序或席位分配" },
  draftTitle: { en: "Request package", zh: "请求包" },
  draftNotSubmitted: { en: "Draft only · not submitted", zh: "仅草稿 · 尚未提交" },
  draftSaved: { en: "Draft saved · not submitted", zh: "草稿已保存 · 尚未提交" },
  draftLocalOnly: { en: "Local-only draft", zh: "仅限当前会话的草稿" },
  draftReadyCopy: {
    en: "The package is recoverable on this device. Copy it into your authenticated integration; no randomness has been requested yet.",
    zh: "请求包会保存在本设备，可复制到已认证的集成中；此时尚未请求任何随机数。",
  },
  draftLocalOnlyCopy: {
    en: "This request exists only in the current session. Copy it now or retry after local recovery storage is available; no randomness has been requested.",
    zh: "此请求仅存在于当前会话。请立即复制，或在本地恢复存储可用后重试；此时尚未请求任何随机数。",
  },
  storageUnavailableCopy: {
    en: "The workbench remains usable, but this device did not confirm an exact local write and delete readback. A draft or pasted response may not survive reload.",
    zh: "工作台仍可使用，但本设备未能确认本地写入与删除的精确回读。草稿或粘贴的回执可能无法在刷新后恢复。",
  },
  buildDraft: { en: "Build request draft", zh: "生成请求草稿" },
  buildingDraft: { en: "Building draft", zh: "正在生成草稿" },
  clearDraft: { en: "Clear draft", zh: "清除草稿" },
  copyRequest: { en: "Copy request", zh: "复制请求" },
  copied: { en: "Copied", zh: "已复制" },
  copyUnavailable: {
    en: "Clipboard access is unavailable. Select the payload and copy it manually.",
    zh: "剪贴板不可用，请选中请求载荷并手动复制。",
  },
  requestId: { en: "Request ID", zh: "请求 ID" },
  endpoint: { en: "Endpoint", zh: "端点" },
  method: { en: "Method", zh: "方法" },
  targetChain: { en: "Target chain", zh: "目标链" },

  drawerRequest: { en: "Request", zh: "请求" },
  drawerService: { en: "Service", zh: "服务" },
  drawerVerify: { en: "Verify", zh: "验证" },
  drawerPayload: { en: "Payload", zh: "载荷" },
  advancedContext: { en: "Local request context", zh: "本地请求上下文" },
  advancedContextCopy: {
    en: "These labels help your team identify the draft. They are not fields in the Morpheus /vrf/random body and are not signed by the response.",
    zh: "这些标签用于团队识别草稿，不属于 Morpheus /vrf/random 请求体，也不会被回执签名。",
  },
  consumer: { en: "Consumer label", zh: "消费者标签" },
  consumerPlaceholder: { en: "miniapp-oracle-vrf-console", zh: "miniapp-oracle-vrf-console" },
  reference: { en: "Round or job reference", zh: "回合或任务标识" },
  referencePlaceholder: { en: "season-7-final", zh: "season-7-final" },
  exactPayloadTitle: { en: "Exact service request", zh: "准确的服务请求" },
  exactPayloadCopy: {
    en: "Only this JSON body is submitted to POST /vrf/random. Building or copying it is not a service request.",
    zh: "仅此 JSON 请求体会提交到 POST /vrf/random。生成或复制它不代表已发起服务请求。",
  },

  verifyTitle: { en: "Signed response verifier", zh: "签名回执验证器" },
  verifyCopy: {
    en: "Paste the complete Morpheus JSON response. Verification pins the signature to the selected network's worker key and recomputes the canonical randomness hash; the chain fulfillment key is checked separately.",
    zh: "粘贴完整的 Morpheus JSON 回执。验证器会把签名绑定到所选网络的 worker 密钥并重新计算随机数规范哈希；链上履约密钥会单独检查。",
  },
  responseLabel: { en: "Response JSON", zh: "回执 JSON" },
  responsePlaceholder: { en: "Paste the signed /vrf/random response…", zh: "粘贴已签名的 /vrf/random 回执…" },
  verifyResponse: { en: "Verify signed response", zh: "验证签名回执" },
  verifyingResponse: { en: "Verifying response", zh: "正在验证回执" },
  verificationEmpty: { en: "No response verified", zh: "尚未验证回执" },
  verificationEmptyCopy: { en: "Build a draft, submit it through your integration, then paste the returned JSON here.", zh: "先生成草稿，通过您的集成提交，再把返回的 JSON 粘贴到这里。" },
  verificationVerified: { en: "Signed randomness verified", zh: "随机数签名已验证" },
  verificationUnbound: { en: "Valid signature, wrong request", zh: "签名有效，但请求不匹配" },
  verificationInvalid: { en: "Response rejected", zh: "回执已拒绝" },
  verificationBlocked: { en: "Refresh key evidence first", zh: "请先刷新密钥证据" },
  verificationSignedScope: {
    en: "The signature covers only the canonical randomness value. request_id and timestamp are correlation metadata, not signed fields.",
    zh: "签名仅覆盖规范化的 randomness 值。request_id 与 timestamp 是关联元数据，不属于签名字段。",
  },
  attestationLimited: {
    en: "Attestation hash binding is inspected, but this client does not independently validate the complete Nitro certificate/PCR chain.",
    zh: "客户端会检查证明哈希绑定，但不会独立验证完整的 Nitro 证书/PCR 链。",
  },
  checkSchema: { en: "Canonical response schema", zh: "规范回执结构" },
  checkRequest: { en: "Request correlation", zh: "请求关联" },
  checkMethod: { en: "CSPRNG signed method", zh: "CSPRNG 签名方式" },
  checkNetworkKey: { en: "Pinned response signer", zh: "固定的回执签名密钥" },
  checkOutputHash: { en: "Randomness output hash", zh: "随机数输出哈希" },
  checkSignature: { en: "secp256r1 signature", zh: "secp256r1 签名" },
  checkAttestation: { en: "Attestation scope", zh: "证明范围" },
  checkPass: { en: "Pass", zh: "通过" },
  checkFail: { en: "Fail", zh: "失败" },
  checkInfo: { en: "Limited", zh: "有限验证" },

  reasonServiceKey: { en: "The selected network's pinned Morpheus response signer is unavailable.", zh: "所选网络固定的 Morpheus 回执签名密钥不可用。" },
  reasonTooLarge: { en: "The response exceeds the 64 KB verification limit.", zh: "回执超过 64 KB 的验证上限。" },
  reasonJson: { en: "The response is not valid JSON.", zh: "回执不是有效 JSON。" },
  reasonSchema: { en: "Required canonical envelope fields are missing or inconsistent.", zh: "规范信封字段缺失或不一致。" },
  reasonRequest: { en: "The response request_id does not match the active draft.", zh: "回执 request_id 与当前草稿不匹配。" },
  reasonMethod: { en: "Only csprng-signed responses are accepted.", zh: "仅接受 csprng-signed 回执。" },
  reasonSigner: { en: "The signer does not match the selected network's Morpheus worker key.", zh: "签名者与所选网络的 Morpheus worker 密钥不匹配。" },
  reasonHash: { en: "The canonical randomness hash does not match the envelope.", zh: "随机数规范哈希与信封不匹配。" },
  reasonSignature: { en: "The secp256r1 signature is invalid.", zh: "secp256r1 签名无效。" },

  statusReady: { en: "Ready for a request draft", zh: "可以生成请求草稿" },
  statusCheckingService: { en: "Checking service and chain bindings", zh: "正在检查服务与链上绑定" },
  statusServiceRefreshed: { en: "Service boundary refreshed", zh: "服务边界已刷新" },
  statusServiceRefreshFailed: { en: "Live refresh failed; cached evidence is marked stale", zh: "实时刷新失败；缓存证据已标记为过期" },
  statusDraftReady: { en: "Draft ready — nothing submitted", zh: "草稿已生成 — 尚未提交" },
  statusDraftReadyLocalOnly: { en: "Draft ready in this session; local recovery is unavailable", zh: "草稿已在当前会话生成；本地恢复不可用" },
  statusDraftRecovered: { en: "Recovered a local draft — nothing submitted", zh: "已恢复本地草稿 — 尚未提交" },
  statusDraftCleared: { en: "Local draft cleared", zh: "本地草稿已清除" },
  statusDraftClearUnconfirmed: { en: "Draft cleared in this session; stored deletion could not be confirmed", zh: "当前会话中的草稿已清除；无法确认已删除存储记录" },
  statusOperationBusy: { en: "Finish the current workbench action first", zh: "请先完成当前工作台操作" },
  statusVerificationContextChanged: { en: "The draft or response signer changed; verify the response again", zh: "草稿或回执签名密钥已变化；请重新验证回执" },
  secureNonceUnavailable: { en: "Secure request identity is unavailable in this browser context", zh: "当前浏览器环境无法生成安全的请求标识" },
  statusResponseVerified: { en: "Signed randomness verified against the network-pinned worker key", zh: "随机数签名已使用网络固定的 worker 密钥验证" },
  statusResponseUnbound: { en: "Signature is valid, but the response belongs to a different request", zh: "签名有效，但回执属于另一个请求" },
  statusResponseInvalid: { en: "Response verification failed", zh: "回执验证失败" },
  statusVerificationBlocked: { en: "The network-pinned response signer is unavailable", zh: "网络固定的回执签名密钥不可用" },

  docsTitle: { en: "What this workbench proves", zh: "本工作台能证明什么" },
  docsSubtitle: {
    en: "This is a read-only request and verification workbench. It does not connect a wallet, submit a transaction, POST to the protected VRF route, or claim a local draft is fulfilled.",
    zh: "这是只读的请求与验证工作台。它不会连接钱包、提交交易、向受保护的 VRF 路由发起 POST，也不会把本地草稿声称为已完成请求。",
  },
  feature1Name: { en: "Exact request", zh: "准确请求" },
  feature1Desc: {
    en: "The service body contains only request_id and target_chain=neo_n3. Use-case labels remain local context.",
    zh: "服务请求体只包含 request_id 与 target_chain=neo_n3；使用场景标签仅保留为本地上下文。",
  },
  feature2Name: { en: "Live binding checks", zh: "实时绑定检查" },
  feature2Desc: {
    en: "Health, runtime status, the worker response signer, the separate fulfillment verifier, request counters, and callback binding are checked without writes.",
    zh: "以只读方式检查健康状态、运行时状态、worker 回执签名密钥、独立履约验证密钥、请求计数和回调绑定。",
  },
  feature3Name: { en: "Bound signature verification", zh: "绑定式签名验证" },
  feature3Desc: {
    en: "The verifier recomputes SHA-256 over the canonical randomness object, pins the secp256r1 signer to the selected network, and separately checks the unsigned request correlation. Full Nitro attestation-chain validation is outside this client.",
    zh: "验证器会重新计算规范 randomness 对象的 SHA-256，把 secp256r1 签名者绑定到所选网络，并单独检查未签名的请求关联。完整 Nitro 证明链验证不在本客户端范围内。",
  },
} as const;

export const messages = mergeMessages(appMessages);
