/**
 * @deprecated Import from "@shared/constants" (index.ts) instead.
 *
 * This file re-exports canonical constants for backward compatibility.
 * All definitions now live in index.ts to avoid duplication.
 */
export {
  TIME_CONSTANTS,
  TOKEN_CONSTANTS,
  BLOCKCHAIN_CONSTANTS,
  UI_CONSTANTS,
  VALIDATION_CONSTANTS,
  BREAKPOINTS,
  CONTRACT_LIMITS,
} from "./index";

// Legacy aliases — kept so existing imports keep compiling.
import {
  TIME_CONSTANTS,
  TOKEN_CONSTANTS,
  UI_CONSTANTS,
  VALIDATION_CONSTANTS,
  BREAKPOINTS,
  CONTRACT_LIMITS,
} from "./index";

/** @deprecated Use TIME_CONSTANTS */
export const TIME = {
  MS_PER_SECOND: TIME_CONSTANTS.SECOND_MS,
  SECONDS_PER_MINUTE: 60,
  MINUTES_PER_HOUR: 60,
  HOURS_PER_DAY: 24,
  SECONDS_PER_DAY: TIME_CONSTANTS.SECONDS_PER_DAY,
  MS_PER_DAY: TIME_CONSTANTS.DAY_MS,
  DAYS_PER_YEAR: TIME_CONSTANTS.DAYS_PER_YEAR,
  DAYS_PER_LEAP_YEAR: 366,
  DEFAULT_TIMEOUT_MS: TIME_CONSTANTS.DEFAULT_TIMEOUT_MS,
  CELEBRATION_DURATION_MS: TIME_CONSTANTS.CELEBRATION_DURATION_MS,
  DEBOUNCE_DELAY_MS: UI_CONSTANTS.SEARCH_DEBOUNCE_MS,
  ANIMATION_DURATION_MS: 500,
} as const;

/** @deprecated Use TOKEN_CONSTANTS / CONTRACT_LIMITS */
export const GAME = {
  MAX_BET_GAS: TOKEN_CONSTANTS.MAX_BET_AMOUNT,
  MIN_BET_GAS: 0.01,
  DEFAULT_FEE_BPS: 50,
  MAX_FEE_BPS: CONTRACT_LIMITS.MAX_FEE_BPS,
  BASIS_POINTS_DIVISOR: CONTRACT_LIMITS.BASIS_POINTS_DIVISOR,
  GAS_DECIMALS: TOKEN_CONSTANTS.GAS_DECIMALS,
  NEO_DECIMALS: TOKEN_CONSTANTS.NEO_DECIMALS,
} as const;

/** @deprecated Use VALIDATION_CONSTANTS */
export const LIMITS = {
  MAX_NAME_LENGTH: 100,
  MAX_DESCRIPTION_LENGTH: 1000,
  MAX_MEMO_LENGTH: VALIDATION_CONSTANTS.MAX_TX_MEMO_LENGTH,
  MAX_PHOTOS_PER_UPLOAD: 5,
  MAX_FILE_SIZE_MB: 10,
  MAX_RETRIES: 3,
  MIN_PASSWORD_LENGTH: VALIDATION_CONSTANTS.MIN_PASSWORD_LENGTH,
} as const;

/** @deprecated Use CONTRACT_LIMITS */
export const CONTRACT = {
  MAX_LOCK_DAYS: CONTRACT_LIMITS.MAX_LOCK_DAYS,
  MAX_MILESTONES: CONTRACT_LIMITS.MAX_MILESTONES,
  DEFAULT_GAS_PRICE: CONTRACT_LIMITS.DEFAULT_GAS_PRICE,
} as const;

/** @deprecated Use individual constant objects */
export const CONSTANTS = {
  TIME,
  BREAKPOINTS,
  GAME,
  LIMITS,
  CONTRACT,
} as const;

/** @deprecated Use BREAKPOINTS / TIME_CONSTANTS directly */
export const DEFAULTS = {
  DESKTOP_BREAKPOINT: BREAKPOINTS.TABLET,
  MOBILE_BREAKPOINT: BREAKPOINTS.MOBILE,
  ANIMATION_DURATION: TIME.ANIMATION_DURATION_MS,
  TIMEOUT_MS: TIME_CONSTANTS.DEFAULT_TIMEOUT_MS,
} as const;
